name: flutter_tailwind_ui_app
description: "Flutter Tailwind UI Example Application"
publish_to: 'none'
version: 0.0.0+0

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.33.0"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_app_info: ^3.0.2
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  flutter_tailwind_ui:
    path: ../
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.10.0
  go_router: ^16.2.4
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  window_manager: ^0.5.1

dev_dependencies:
  analyzer: 8.1.1
  build_runner: ^2.7.0
  flutter_launcher_icons: ^0.14.4
  source_gen: ^4.0.0
  very_good_analysis: ^10.0.0
  
# Icon generation settings
flutter_icons:
  # flutter pub run flutter_launcher_icons
  macos:
    generate: true
    image_path: assets/launcher/icon_mac.png

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
    - assets/img/

