name: flutter_tailwind_ui_example
description: "Flutter Tailwind UI Example Application"
publish_to: 'none'
version: 1.0.0+1
topics:
  - user-interface
  - design-system
  - flutter-ui

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_app_info: ^2.0.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  flutter_tailwind_ui:
    path: ../
  font_awesome_flutter: ^10.7.0
  
  go_router: ^14.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
    - assets/img/

