include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    cascade_invocations: false
    omit_local_variable_types: false
    one_member_abstracts: false
    avoid_positional_boolean_parameters: false