name: flutter_tailwind_ui
description: "Flutter widgets, theming, standards, and design system inspired by Tailwind UI"
version: 0.0.3
maintainer: Taza Technology LLC
homepage: https://fluttertailwind.com
documentation: https://fluttertailwind.com
repository: https://github.com/tazatechnology/flutter-tailwind-ui
issue_tracker: https://github.com/tazatechnology/flutter-tailwind-ui/issues
topics:
  - user-interface
  - design-system
  - flutter-ui
  
environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  syntax_highlight: ^0.4.0
  url_launcher: ^6.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  assets:
    - grammar/
  fonts:
    # https://github.com/vercel/geist-font/releases/download/1.4.0/Geist-v1.4.0.zip
    - family: Geist
      fonts:
        - asset: fonts/Geist-Thin.ttf
          weight: 100
        - asset: fonts/Geist-ExtraLight.ttf
          weight: 200
        - asset: fonts/Geist-Light.ttf
          weight: 300
        - asset: fonts/Geist-Regular.ttf
          weight: 400
        - asset: fonts/Geist-Medium.ttf
          weight: 500
        - asset: fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: fonts/Geist-Bold.ttf
          weight: 700
        - asset: fonts/Geist-ExtraBold.ttf
          weight: 800
        - asset: fonts/Geist-Black.ttf
          weight: 900
    # https://github.com/JetBrains/JetBrainsMono/releases/download/v2.304/JetBrainsMono-2.304.zip
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: fonts/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: fonts/JetBrainsMono-Light.ttf
          weight: 300
        - asset: fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: fonts/JetBrainsMono-ExtraBold.ttf
          weight: 900

