name: flutter_tailwind_ui
description: "Flutter widgets and theming inspired by Tailwind UI"
version: 0.0.1
homepage: https://github.com/tazatechnology/flutter-tailwind-ui
repository: https://github.com/tazatechnology/flutter-tailwind-ui

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

