name: flutter_tailwind_ui
description: "Flutter widgets and theming inspired by Tailwind UI"
version: 0.0.1
homepage: https://github.com/tazatechnology/flutter-tailwind-ui
repository: https://github.com/tazatechnology/flutter-tailwind-ui

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  animations: ^2.0.11
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  fonts:
    # https://github.com/vercel/geist-font/releases/download/1.4.0/Geist-v1.4.0.zip
    - family: Geist
      fonts:
        - asset: fonts/Geist-Thin.ttf
          weight: 100
        - asset: fonts/Geist-ExtraLight.ttf
          weight: 200
        - asset: fonts/Geist-Light.ttf
          weight: 300
        - asset: fonts/Geist-Regular.ttf
          weight: 400
        - asset: fonts/Geist-Medium.ttf
          weight: 500
        - asset: fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: fonts/Geist-Bold.ttf
          weight: 700
        - asset: fonts/Geist-ExtraBold.ttf
          weight: 800
        - asset: fonts/Geist-Black.ttf
          weight: 900
    # https://github.com/vercel/geist-font/releases/download/1.4.0/GeistMono-v1.4.0.zip
    - family: GeistMono
      fonts:
        - asset: fonts/GeistMono-Thin.ttf
          weight: 100
        - asset: fonts/GeistMono-UltraLight.ttf
          weight: 200
        - asset: fonts/GeistMono-Light.ttf
          weight: 300
        - asset: fonts/GeistMono-Regular.ttf
          weight: 400
        - asset: fonts/GeistMono-Medium.ttf
          weight: 500
        - asset: fonts/GeistMono-SemiBold.ttf
          weight: 600
        - asset: fonts/GeistMono-Bold.ttf
          weight: 700
        - asset: fonts/GeistMono-UltraBlack.ttf
          weight: 800
        - asset: fonts/GeistMono-Black.ttf
          weight: 900
