# Continuous Deployment: Publish Website to GitHub Pages
name: CD Website
concurrency:
  group: cd-website
  cancel-in-progress: false
  
on:
  push:
    branches: ["main"]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

# Modify the default permissions granted to GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.sha }}
          fetch-depth: 0
          
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Flutter Setup
        uses: ./.github/actions/flutter-setup

      - name: Build Website
        working-directory: example
        run: |
          flutter pub get
          flutter build web \
            --release \
            --tree-shake-icons \
            --pwa-strategy=none \
            --build-name=$(make tag | sed 's/^v//') \
            --build-number=$(make sha)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "example/build/web"
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
