# Continuous Deployment: Publish Package to pub.dev
name: CD Publish
concurrency:
  group: cd-publish
  cancel-in-progress: false

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

# Modify the default permissions granted to GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@main