# Continuous Integration: Tests and Checks
name: CI Test

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

# Modify the default permissions granted to GITHUB_TOKEN
permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  test-package:
    name: test-package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Flutter Setup
        uses: ./.github/actions/flutter-setup

      - name: Install Dependencies
        run: make init

      - name: Analyze Package
        run: make analyze

      - name: Format Package
        run: make format-ci

      - name: Run Package Tests
        run: make test

      - name: Publish Dry Run
        run: flutter pub publish --dry-run

  test-example:
    name: test-example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Flutter Setup
        uses: ./.github/actions/flutter-setup

      - name: Install Dependencies
        working-directory: example
        run: make init

      - name: Build Web Application
        working-directory: example
        run: make build-web

      - name: Analyze Example
        working-directory: example
        run: make analyze

      - name: Format Example
        working-directory: example
        run: make format-ci
