name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main

# Modify the default permissions granted to GITHUB_TOKEN
permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  Publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get Id Token
        uses: actions/github-script@v6
        with:
          script: |
            let pub_token = await core.getIDToken('https://pub.dev')
            core.exportVariable('PUB_TOKEN', pub_token)

      - name: Authenticate
        run: flutter pub pub token add https://pub.dev --env-var PUB_TOKEN
